// acciones de login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_CON_EXITO = "LOGIN_CON_EXITO";
export const LOGIN_CON_ERROR = "LOGIN_CON_ERROR";
export const RECUPERAR_CONTRASENA_CON_EXITO = "RECUPERAR_CONTRASENA_CON_EXITO";

// acciones de cambiar contraseña
export const ABRIR_DIALOG_CAMBIAR_CONTRASENA = "ABRIR_DIALOG_CAMBIAR_CONTRASENA";
export const CERRAR_DIALOG_CAMBIAR_CONTRASENA = "CERRAR_DIALOG_CAMBIAR_CONTRASENA";
export const CAMBIAR_CONTRASENA_START = "CAMBIAR_CONTRASENA_START";
export const CAMBIAR_CONTRASENA_CON_EXITO = "CAMBIAR_CONTRASENA_CON_EXITO";
export const CAMBIAR_CONTRASENA_CON_ERROR = "CAMBIAR_CONTRASENA_CON_ERROR";

// acciones de perfil
export const CARGAR_PERFIL_CON_EXITO = "CARGAR_PERFIL_CON_EXITO";
export const CARGAR_PERFIL_CON_ERROR = "CARGAR_PERFIL_CON_ERROR";

// acciones de multas
export const CARGAR_MULTAS_CON_EXITO = "CARGAR_MULTAS_CON_EXITO";
export const CARGAR_MULTAS_CON_ERROR = "CARGAR_MULTAS_CON_ERROR";

// acciones de filtro
export const ABRIR_DIALOG_FILTRO = "ABRIR_DIALOG_FILTRO";
export const CERRAR_DIALOG_FILTRO = "CERRAR_DIALOG_FILTRO";
export const SET_FILTROS = "SET_FILTROS";
export const CLEAR_FILTROS = "CLEAR_FILTROS";

// acciones de multa
export const CARGAR_MULTA_START = "CARGAR_MULTA_START";
export const CARGAR_MULTA_CON_EXITO = "CARGAR_MULTA_CON_EXITO";
export const CARGAR_MULTA_CON_ERROR = "CARGAR_MULTA_CON_ERROR";

// acciones de resolver multa
export const ABRIR_DIALOG_RESOLVER = "ABRIR_DIALOG_RESOLVER";
export const CERRAR_DIALOG_RESOLVER = "CERRAR_DIALOG_RESOLVER";
export const SET_MULTA_A_RESOLVER = "SET_MULTA_A_RESOLVER";
export const RESOLVER_MULTA_START = "RESOLVER_MULTA_START";
export const RESOLVER_MULTA_CON_EXITO = "RESOLVER_MULTA_CON_EXITO";
export const RESOLVER_MULTA_CON_ERROR = "RESOLVER_MULTA_CON_ERROR";

// acciones de usuarios
export const CARGAR_USUARIOS_CON_EXITO = "CARGAR_USUARIOS_CON_EXITO";
export const CARGAR_USUARIOS_CON_ERROR = "CARGAR_USUARIOS_CON_ERROR";

// acciones de editar usuario
export const ABRIR_DIALOG_EDITAR = "ABRIR_DIALOG_EDITAR";
export const CERRAR_DIALOG_EDITAR = "CERRAR_DIALOG_EDITAR";
export const EDITAR_USUARIO_START = "EDITAR_USUARIO_START";
export const EDITAR_USUARIO_CON_EXITO = "EDITAR_USUARIO_CON_EXITO";
export const EDITAR_USUARIO_CON_ERROR = "EDITAR_USUARIO_CON_ERROR";

// acciones de eliminar usuario
export const ABRIR_DIALOG_ELIMINAR = "ABRIR_DIALOG_ELIMINAR";
export const CERRAR_DIALOG_ELIMINAR = "CERRAR_DIALOG_ELIMINAR";
export const SET_USUARIO_A_ELIMINAR = "SET_USUARIO_A_ELIMINAR";
export const ELIMINAR_USUARIO_START = "ELIMINAR_USUARIO_START";
export const ELIMINAR_USUARIO_CON_EXITO = "ELIMINAR_USUARIO_CON_EXITO";
export const ELIMINAR_USUARIO_CON_ERROR = "ELIMINAR_USUARIO_CON_ERROR";

// acciones de usuario
export const CARGAR_USUARIO_START = "CARGAR_USUARIO_START";
export const CARGAR_USUARIO_CON_EXITO = "CARGAR_USUARIO_CON_EXITO";
export const CARGAR_USUARIO_CON_ERROR = "CARGAR_USUARIO_CON_ERROR";