export const LOGIN_START = "LOGIN_START";
export const LOGIN_CON_EXITO = "LOGIN_CON_EXITO";
export const LOGIN_CON_ERROR = "LOGIN_CON_ERROR";
export const RECUPERAR_CONTRASENA_CON_EXITO = "RECUPERAR_CONTRASENA_CON_EXITO";

export const CARGAR_MULTAS_CON_EXITO = "CARGAR_MULTAS_CON_EXITO";
export const CARGAR_MULTAS_CON_ERROR = "CARGAR_MULTAS_CON_ERROR";

export const CARGAR_MULTA_CON_EXITO = "CARGAR_MULTA_CON_EXITO";
export const CARGAR_MULTA_CON_ERROR = "CARGAR_MULTA_CON_ERROR";
export const CAMBIAR_ESTADO_CON_EXITO = "CAMBIAR_ESTADO_CON_EXITO";
export const CAMBIAR_ESTADO_CON_ERROR = "CAMBIAR_ESTADO_CON_ERROR";

export const CARGAR_USUARIOS_CON_EXITO = "CARGAR_USUARIOS_CON_EXITO";
export const CARGAR_USUARIOS_CON_ERROR = "CARGAR_USUARIOS_CON_ERROR";

export const CREAR_USUARIO_START = "CREAR_USUARIO_START";
export const CREAR_USUARIO_CON_EXITO = "CREAR_USUARIO_CON_EXITO";
export const CREAR_USUARIO_CON_ERROR = "CREAR_USUARIO_CON_ERROR";